--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PrismStudioMC/PrismArea
build-by-default: true
branches:
- main
projects:
  PrismArea:
    path: ""
    lint:
      phpstan: false
...
